# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DevOps2.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  mqPackagePath: 'Installer/'
  mqInstallationPath: 'C:\Installation\ActiveQ'
  mqPackage: 'apache-activemq-5.15.10'

stages:
 - stage: build
   displayName: 'Build Solution'
   jobs:
   - job: 'Build'
     pool:
      vmImage: 'windows-latest'
     steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.SourcesDirectory)/$(mqPackagePath)'
            artifact: 'drop'
            publishLocation: 'pipeline'
   
 - stage: Dev
   displayName: 'Deploy On premise'
   jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      environment: 
        name: infra
        resourceType: VirtualMachine
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            steps:
                - task: CopyFiles@2
                  inputs:
                    SourceFolder: '$(Pipeline.Workspace)/drop'
                    Contents: '**'
                    TargetFolder: '$(mqInstallationPath)'
                    CleanTargetFolder: true
                    OverWrite: true
                    
                - task: BatchScript@1
                  inputs:
                    filename: '$(mqInstallationPath)\$(mqPackage)\bin\win64\InstallService.bat'
                    failOnStandardError: true
                    
                - task: CmdLine@2
                  inputs:
                    script: 'net start ActiveMQ'
                    failOnStderr: true