# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

parameters:
- name: env
  displayName: Enviornments
  type: string
  default: PTE1
  values:
  - PTE1
  - PTE2
  - PPE
  - PROD

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/DevOps2.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  mqInstallationPath: 'C:\Installation\ActiveMQ'
  mqPackage: 'apache-activemq-5.15.10'
stages:
 - stage: build
   displayName: 'Build Solution'
   jobs:
   - job: 'Build'
     pool:
      vmImage: 'windows-latest'
     steps:
#        - task: NuGetToolInstaller@1

#        - task: NuGetCommand@2
#          inputs:
#            restoreSolution: '$(solution)'

#        - task: VSBuild@1
#          inputs:
#            solution: '$(solution)'
#            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'
#            platform: '$(buildPlatform)'
#            configuration: '$(buildConfiguration)'

#        - publish: '$(Build.ArtifactStagingDirectory)'
#          displayName: 'Publish'
#          artifact: drop   

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.SourcesDirectory)/Installer/apache-activemq-5.15.10-bin.zip'
            artifact: 'drop'
            publishLocation: 'pipeline'

 - stage: Dev
   displayName: 'Deploy On premise'
   jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      environment: 
        name: infra
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:

#            - task: CmdLine@2
#              inputs:
#                script: 'activemq start'
#                workingDirectory: 'C:\Installer\apache-activemq-5.15.10-bin\apache-activemq-5.15.10\bin'
#            - task: BatchScript@1
#              inputs:
#                filename: 'C:\Installer\apache-activemq-5.15.10-bin\apache-activemq-5.15.10\bin\win64\InstallService.bat'
#                failOnStandardError: true

            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: '$(Pipeline.Workspace)/drop/*.zip'
                destinationFolder: '$(mqInstallationPath)'
                cleanDestinationFolder: true
                overwriteExistingFiles: false

            - task: BatchScript@1
              inputs:
                filename: '$(mqInstallationPath)\$(mqPackage)\bin\win64\InstallService.bat'
                failOnStandardError: true
                
            - task: CmdLine@2
              inputs:
                script: 'net start ActiveMQ'
                failOnStderr: true